spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  activiti:
    check-process-definitions: false
    history-level: full
    db-history-used: true
    database-schema-update: true

server:
  port: 8081 